# -*- coding: utf-8 -*-
"""Rushali_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-O3nBgUpEGC5npuA0KkFn8_vkxNdCjn

# 📦 Delivery Time Prediction for RapidLogistics

This project builds a Machine Learning model to predict delivery time for shipments based on package details, transport type, and delay factors like traffic and weather.
"""

## Step 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

## Step 2: Load the Dataset
df = pd.read_csv("Delivery Time Prediction for RapidLogistics.csv")
df.head()

## Step 3: Data Preprocessing
# Check for null values
print("Null Values Check:\n", df.isnull().sum())

# Create separate LabelEncoders
le_origin = LabelEncoder()
le_dest = LabelEncoder()
le_mode = LabelEncoder()

# Encode categorical variables
df['origin_city'] = le_origin.fit_transform(df['origin_city'])
df['destination_city'] = le_dest.fit_transform(df['destination_city'])
df['transport_mode'] = le_mode.fit_transform(df['transport_mode'])

# Drop shipment_id
df.drop('shipment_id', axis=1, inplace=True)

## Step 4: Feature and Target Split
X = df.drop('estimated_delivery_time_hrs', axis=1)
y = df['estimated_delivery_time_hrs']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Step 5: Model Training
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

## Step 6: Model Evaluation
y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

## Step 7: Predict New Delivery Time (Sample)
sample = pd.DataFrame({
    'origin_city': [le_origin.transform(['Delhi'])[0]],
    'destination_city': [le_dest.transform(['Chennai'])[0]],
    'package_weight_kg': [12],
    'package_size_cu_m': [0.6],
    'transport_mode': [le_mode.transform(['Air'])[0]],
    'historical_avg_delivery_time_hrs': [18],
    'traffic_delay_hrs': [1.2],
    'weather_delay_hrs': [0.3]
})

predicted_time = model.predict(sample)
print("Predicted Delivery Time:", predicted_time[0], "hours")